### ISSUE TITLE
Count() warning: parameter must be an array or an object that implements countable

### ISSUE THREAD

**Issue by benpolman** [edeso/SecureInclude#2]
In secure-include.php line 319
  if (! isset($haystack_list) ||  count($haystack_list) == 0) {
Will produce the warning with php >= 7.4
Replace by
  if (! isset($haystack_list) || ( is_array($haystack_list) && count($haystack_list) == 0)) {

Or alter the order since you can continue with explicitly converting to array if a string is provided.

**Comment by edeso** [comment]
should be fixed in master. can you please try?

**Comment by benpolman** [comment]
Done and it works, thx
